# Generated by Django 3.2.9 on 2021-11-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('open_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('open_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('open_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.test1')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='empty', max_length=100)),
                ('target_dorm', models.CharField(default='empty', max_length=100)),
                ('host_student', models.CharField(default='empty', max_length=100)),
                ('in_time', models.DateTimeField(default=None, null=True)),
                ('out_time', models.DateTimeField(default=None, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.guest')),
            ],
        ),
    ]
