version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "
      gunicorn -w4 -b :5000 --log-level=debug manage:app"
    volumes:
      - .:/code
    container_name: app
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "/home/ubuntu/mysql/:/var/lib/mysql"
    expose:
      - "3306"
    env_file: .env
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - static-volume:/code/application/static
      - templates-volume:/code/application/templates
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
  templates-volume:
