# Generated by Django 3.2.9 on 2021-12-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='empty', max_length=100)),
                ('host_student', models.CharField(default='empty', max_length=100)),
                ('in_time', models.DateTimeField(default=None, null=True)),
                ('out_time', models.DateTimeField(default=None, null=True)),
                ('approval', models.CharField(default='pending', max_length=20)),
                ('dorm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_dorm', to='dorm.dorm')),
                ('dormbuilding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_dormbuilding', to='dorm.dormbuilding')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_log', to='guest.guest')),
            ],
        ),
    ]
