# Generated by Django 3.2.9 on 2021-11-23 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='empty', max_length=100)),
                ('target_dorm', models.CharField(default='empty', max_length=100)),
                ('host_student', models.CharField(default='empty', max_length=100)),
                ('in_time', models.DateTimeField(default=None, null=True)),
                ('out_time', models.DateTimeField(default=None, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest.guest')),
            ],
        ),
    ]
