# Generated by Django 3.2.9 on 2021-12-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DormBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='紫荆1号楼', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student1', models.CharField(default='empty', max_length=20)),
                ('student2', models.CharField(default='empty', max_length=20)),
                ('student3', models.CharField(default='empty', max_length=20)),
                ('student4', models.CharField(default='empty', max_length=20)),
                ('dormbuilding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dorm_Building', to='dorm.dormbuilding')),
            ],
        ),
    ]
