# Generated by Django 3.2.9 on 2021-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('open_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
