# Generated by Django 3.2.9 on 2021-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('open_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('department', models.CharField(default=None, max_length=20, null=True)),
                ('student_id', models.CharField(default=None, max_length=12, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('credit', models.BooleanField(default=True)),
            ],
        ),
    ]
